version: '3.8'
services:

  php-apache:
    container_name: Historial-apache
    image: php:8.2-apache
    build: ./
    volumes:
      - ./:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "${APACHE_PORT:-8060}:80" # Set a default port if not provided
    depends_on:
      - db

  db:
    container_name: Historial-db
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root} # Set a default value if not provided
    volumes:
      - ./mysql:/var/lib/mysql # Use named volumes for data persistence

  phpmyadmin:
    container_name: Historial-phpmyadmin
    image: phpmyadmin:5.2
    environment:
      PMA_HOST: db
    ports:
      - "${PMA_PORT:-8061}:80" # Set a default port if not provided
    depends_on:
      - db

volumes:
  mysql: # Define a named volume for MySQL data persistence
